* basics
  HTML stands for Hyper Text Markup Language.
  A markup language is a set of markup tags.
  HTML documents are described by HTML tags.
  Each HTML tag describes different document content.

  The text between <HTML> and </HTML> describes an HTML document.
  The text between <head> and </head> provides information about the document.
  The text between <body> and </body> describes the visible page content.

  HTML tags are keywords (tag names) surrounded by angle brackets.

  The browser does not display the HTML tags, but uses them to determine how to
  display the document.

  The <!DOCTYPE> declaration helps the browser to display a web page correctly.
  To display a document correctly, the browser must know both type and version.
  The doctype declaration is not case sensitive.

  HTML tags are not case sensitive.
* HTML element
  HTML documents are made up by HTML elements.

  HTML elements are written with a start tag, with an end tag, with the content
  in between.
  The HTML element is everything from the start tag to the end tag.
  Some HTML elements do not have an end tag.
  HTML elements can be nested (elements can contain elements).
  All HTML documents consist of nested HTML elements.

  The *<HTML>* element defines the *whole document*.
  It has a *start* tag <HTML> and an *end* tag </HTML>.
  The element *content* is another HTML element.

  HTML elements with not content are called *empty elements*.
  Empty element can be "closed" in the opening tag like this: <br />.
* HTML attributes
  HTML elements can have attributes.
  Attributes provide additional information about an element.
  Attributes are always specified in the start tag.
  Attributes come in name/value pairs like: name="value".
* interesting tags
  + <hr>
	The *<hr>* tag creates a horizontal line in an HTML page.
	The hr element can be used to separate content.
  + <style>
	The HTML *<style>* element is used to define internal CSS style sheets.
  + <link>
	The HTML *<link>* element is used to define external CSS style sheets.
  + <p>
	Browsers automatically add an empty line before and after a paragraph.
  + <br>
	Use <br> if you want a line break (a new line) without starting a new
    paragraph.
  + <pre>
	The HTML *<pre>* element defines a block of *pre-formatted* text, with
    structured spaces and lines.
	To display anything, with right spacing and line-breaks, you must wrap the
    text in a *<pre>* element.
  + <mark>
	The HTML *<mark>* element defines marked or highlighted text.
  + <del>
	The HTML *<del>* element defines deleted(removed) of text.
  + <ins>
	The HTML *<ins>* element defines inserted (added) text.
  + <sub>
	The HTML *<sub>* element defines *subscripted* text.
  + <sup>
	The HTML *<sup>* element defines *superscripted* text.
  + <q>
	The HTML *<q>* element defines a short quotation.
	Browsers usually insert *quotation marks* around the <q> element.
  + <blockquote>
	The HTML *<blockquote>* element defines a quoted section.
	Browsers usually indent <blockquote> elements.
  + <abbr>
	The HTML *<abbr>* element defines an abbreviation or an acronym.
	Marking abbreviations can give useful information to browsers, translation
    systems and search-engines.
  + <address>
	The HTML *<address>* element defines contact information (author/owner) of
    a document or article.
	The element is usually displayed in *italic*. Most browsers will add a line
    break before and after the element.
  + <cite>
	The HTML *<cite>* element defines the *title of a work*.
	Browsers usually displays <cite> elements in italic.
  + <kbd>
	The HTML *<kbd>* element defines *keyboard input*.
  + <samp>
	The HTML *<samp>* element defines a computer output sample.
  + <code>
	The HTML *<code>* element defines programming code sample.
	The *<code>* element does not preserve extra whitespace and line-breaks.
  + <var>
	The HTML *<var>* element defines a mathematical variable.

	例:
	<p>Einstein wrote:</p>
	<p><var>E=mc<sup>2</sup></var></p>
* HTML Display
  With HTML, you cannot change the output by adding extra spaces or extra lines
  in your HTML code.
  The browser will remove extra spaces and extra lines when the page is
  displayed.
  Any number of spaces, and any number of new lines, count as only one space.
* HTML comment
  <!-- comment -->
* HTML styling
  Styling can be added to HTML elements in 3 ways:
  + Inline
	using a *style attribute* in HTML elements
  + Internal
	using a *<style> element* in the HTML <head> section
  + External
	using one or more *external CSS files*.
    It's defined in the *<head>* section of an HTML page, in the *<link>*
    element:
	<link rel="stylesheet" href="位置">

  CSS styling has the following syntax:
  
  element {
    property: value;
	property: value;
  }
* CSS Box Model
  Every visible HTML element has a box around it, even if you cannot see it.
  The CSS *border* property defines a visible border around an HTML element.
  The CSS *padding* property defines a padding (space) inside the border.
  The CSS *margin* property defines a margin (space) outside the border.
* HTML links
  A hyperlink is an element, a text, or an image that you can click on, and
  jump to another document.

  The link text does not have to be text. It can be an HTML image or any other
  HTML element.
  
  The *target* attribute specifies where to open the linked document.
  常见的形式:

  <!-- 通过新的页面打开该链接 -->
  <a href="链接" target="_blank">内容</a>

  The *id* attribute can be used to create *bookmarks* inside HTML documents.
  Bookmarks are not displayed in any special way. They are invisible to the
  reader.

  例:
  <a id="tips">Useful Tips Section</a>
  <a herf="#tips">Visit the Useful Tips Section</a>
  Or
  <a href="http://xxx/xx.html#tips">Visit the Useful Tips Seciton</a>
* HTML img
  Always specify image size. If the size is unknown, the page will flicker
  while the image loads.

  The *<img>* tag is empty, it contains attributes only, and does not have a
  closing tag.
  
  The value of the *alt* attribute should describe the image in
  words. The *alt* attribute is *required*. A web page will not validate
  correctly without it.

  Screen readers can read the *alt* attribute.

  If a browser cannot find an image, it will display a broken link icon.
* HTML Screen Readers
  Screen readers are software programs that can read what is displayed on a
  screen.
  Used on the web, screen readers can "reproduce" HTML as text-to-speech, sound
  icons, or braille output.
  Screen readers are used by people who are blind, visually impaired, or
  learing disabled.
* HTML Styling
  Every HTML element has a default style.
  Changing the default style of an HTML element, can be done with the *style*
  attribute.
  
  The HTML style attribute has the following syntax:
    style="property:value"
  The *property* is a CSS property. The *value* is a CSS value.
* references
  + [[http://www.w3schools.com/tags/default.asp][tag]]
  + [[http://www.w3schools.com/tags/ref_standardattributes.asp][global attributes]]
