* Basics
  MongoDB is a *document-oriented* database.

  There are six simple concepts we need to understand:
  1) MongoDB has the same concept of a database with which you are likely
     already familiar.
	 Within a MongoDB instance, you can have zero or more *databases*, each
     acting as high-level containers for everything else.
  2) A database can have zero or more *collections*. A collection shares enough
     in common with a traditional _table_ that you can safely think of the two
     as the same thing.
  3) Collections are made up of zero or more *documents*. Again, a document can
     safely be thought of as a _row_.
  4) A document is made up of one or more *fields*, which you probably guess
     are a lot like _columns_.
  5) *Indexes* in MongoDB function much like their RDBMS counterparts.
  6) *Cursors*: The important thing to understand about cursors is that when
     you ask MongoDB for data, it returns a cursor, which we can do things to,
     such as counting or skipping ahead, without actually pulling down data.

  MongoDB -> collections -> documents -> fields

  MongoDB is made up of databases which contain *collections*. A collection is
  made up of *documents*. Each documents is made up of *fields*. *Collections*
  can be inserted, which improves look up and sorting performance. When we get
  data from MongoDB, we do so through a *cursor* whose actual extension is
  delayed until necessary
* Query Selectors
  A selector is a JSON object, the simplest of which is *{}* which matches all
  documents (*null* works too).
* object id
  共 12 位:
  + 0~3: utc time
  + 4~6: machine
  + 7~8: pid
  + 9~11: inc/random
* 不能解决的问题
  + 数据库事务一致性需求
  + 数据库的写实时性和读实时性的需求
  + 对复杂的 SQL 查询，特别是多表关联查询的需求
* Mongo 模式设计中的问题
  + 是值得为这个对象创建一个集合，还是把这个对象嵌入到其它的集合中?
* 监控工具
  mongo 自带的:
  + mongostat
  + mongotop
	
  第三方:
  + mms
* 查看 mongo 的位数
  $ mongo
  进入后依次执行:
  > use admin
  > db.runCommand("buildInfo")
* pymongo
** 建索引
*** 为多个字段同时建索引
	例:
	col.ensure_index([('url', 1), ('adData.title', -1)])
* 访问 rockmongo 时一直下载 php 文件
  注意下 rockmongo 的 user:group，如果 rockmongo 是放在 root 相关的目录下，则
  rockmongo 的 user:group 都要改为 root:root.
* 删除某个字段
  如:

  db.example.update(
    {},
    { $unset: {'tags.words':1}},
    false, true
  )
* 导出和导入 db
  导出库:
  $ mongodump -d 库名 -o 备份目录名
  
  导入:
  $ mongorestore 备份目录名 
